### ISSUE TITLE
vocabulary.txt file not found

### ISSUE THREAD

**Issue by YerongLi** [NUS-IDS/ranlp21-fiqv#1]
On running the training workflow I am getting this vocabulary not found error. Are you using glove embedding directly?

    FileNotFoundError: [Errno 2] No such file or directory: '~/ranlp21-fiqv/code/data/processed/repeat_q/fipsq_triples/vocabulary.txt'

**Comment by gud111** [comment]
Hi Yerong, apologies, the problem was missing instructions in the readme. There's a step you need to run for extracting the vocabulary and subset of embeddings and the documentation has been updated to reflect the same. 

However, I have also uploaded the files here: https://github.com/NUS-IDS/ranlp21-fiqv/tree/main/processed_data/extra in case you want to try a run with them directly. Thanks for pointing out the problem!

**Comment by YerongLi2** [comment]
Yes, thank you so much, it works.

**Comment by YerongLi** [comment]
Yes, it works. Thank you so much for add the **extra** folder
